version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    command:
      - awscli sqs create-queue --queue-name translate-queue
      - awscli s3api create-bucket --bucket docx-translate
    environment:
      DEBUG: "1"
      SERVICES: "sqs,s3"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis:
    container_name: redis
    image: bitnami/redis-cluster:7.2-debian-12
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "redis"
      REDISCLI_AUTH: "redis"
      REDIS_NODES: "redis"
      REDIS_TLS_ENABLED: "yes"
      REDIS_TLS_PORT_NUMBER: "6379"
      REDIS_TLS_AUTH_CLIENTS: "no"
      REDIS_TLS_CERT_FILE: "/tls/redis.crt"
      REDIS_TLS_KEY_FILE: "/tls/redis.key"
      REDIS_TLS_CA_FILE: "/tls/ca.crt"
    volumes:
      - "./tls/local/redis:/tls"

  postgres:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  api:
    container_name: api
    image: doctranslate-api
    ports:
      - "8080:8080"
    env_file: .local.env
    environment:
      AWS_ENDPOINT: "http://localstack:4566"
      AWS_SQS_QUEUE_URL: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/translate-queue"
      DB_HOST: "postgres"
      REDIS_ADDRS: "redis:6379"
    depends_on:
      - localstack
      - redis
      - postgres
